Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.95.5"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    sudo apt install gnupg2 pass -y
    systemctl enable docker
    systemctl start docker
  SHELL
end
