Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.95.5"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    sudo apt install gnupg2 pass -y
    systemctl enable docker
    systemctl start docker
    sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
  SHELL
end
