apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: 6.3.6
    chart: podinfo
    helm:
      parameters:
        - name: replicaCount
          value: '3'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

