apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.10.3
    chart: redis
    directory:
      jsonnet:
        tlas:
          - {}
    helm:
      parameters:
        - name: auth.password
          value: moshe
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

