pipeline {
	agent any
	stages {
		stage("clean"){
			steps{
				cleanWs()
			}
		}
		stage("clone"){
			steps{
				git "https://github.com/avielb/python-project.git"
			}
		}
		stage("build"){
			steps {
				sh "docker build -t avielb/python-project:latest ."
			}
		}
		stage ("lint") {
			agent {
				docker {
					image 'hadolint/hadolint:latest-debian'
					args " -v ${WORKSPACE}:/workspace"
				}
			}
			steps {
				sh 'cd /workspace && hadolint Dockerfile'
				//    sh 'cd /workspace && hadolint Dockerfile.Bad'

			} //
		}
		stage("scan") {
			steps {
				withCredentials([string(credentialsId: 'SNYK_TOKEN', variable: 'SNYK_TOKEN')]) {
					sh "npm install -g snyk"
					sh "snyk test --docker avielb/python-project:latest"
				}

			}
		}
		stage("push") {
			steps{
				sh "docker push avielb/python-project:latest"
			}
		}
	}
}