version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"   # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3,lambda,dynamodb # List any other services you want to enable here

volumes:
  localstack_volume:
    driver: local
