Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 4096
  end
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    sudo apt install gnupg2 pass -y
    systemctl enable docker
    systemctl start docker
    sudo usermod -aG docker vagrant
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
    runuser -l  vagrant -c 'minikube start'
    echo 'alias kubectl=\"minikube kubectl --\"' >> ~vagrant/.bashrc
    runuser -l  vagrant -c 'minikube kubectl -- get pods'
  SHELL
end
