apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
        - name: nginx
          image: avielb/myimage-2402:v0.2
