apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web

spec:
  replicas: two
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: "eighty"
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: missing-configmap  # ConfigMap doesn't exist
                  key: mode
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: html-files
