# .github/workflows/docker-image-build.yaml
name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/2402-myimage:v0.${{ github.run_number }}

      - name: Update values.yaml with new image tag
        run: |
          echo -e "image:\n  tag: v0.${{ github.run_number }}" > mychart/values-image.yaml
          

      - name: Commit updated values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git status
          git add .
          git commit -m "Update image tag to 0.${{ github.run_number }}"
          git push
